# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import PumpInitialisationService_pb2 as PumpInitialisationService__pb2


class PumpInitialisationServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.InitializePumpDrive = channel.unary_unary(
        '/sila2.de.cetoni.pumps.syringepumps.pumpinitialisationservice.v1.PumpInitialisationService/InitializePumpDrive',
        request_serializer=PumpInitialisationService__pb2.InitializePumpDrive_Parameters.SerializeToString,
        response_deserializer=PumpInitialisationService__pb2.InitializePumpDrive_Responses.FromString,
        )


class PumpInitialisationServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def InitializePumpDrive(self, request, context):
    """Initialize the pump drive (e.g. by executing a reference move).
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PumpInitialisationServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'InitializePumpDrive': grpc.unary_unary_rpc_method_handler(
          servicer.InitializePumpDrive,
          request_deserializer=PumpInitialisationService__pb2.InitializePumpDrive_Parameters.FromString,
          response_serializer=PumpInitialisationService__pb2.InitializePumpDrive_Responses.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sila2.de.cetoni.pumps.syringepumps.pumpinitialisationservice.v1.PumpInitialisationService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
